/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TrackRequestImport } from './routes/track-request'
import { Route as NewRequestImport } from './routes/new-request'
import { Route as ChatImport } from './routes/chat'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const TrackRequestRoute = TrackRequestImport.update({
  id: '/track-request',
  path: '/track-request',
  getParentRoute: () => rootRoute,
} as any)

const NewRequestRoute = NewRequestImport.update({
  id: '/new-request',
  path: '/new-request',
  getParentRoute: () => rootRoute,
} as any)

const ChatRoute = ChatImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatImport
      parentRoute: typeof rootRoute
    }
    '/new-request': {
      id: '/new-request'
      path: '/new-request'
      fullPath: '/new-request'
      preLoaderRoute: typeof NewRequestImport
      parentRoute: typeof rootRoute
    }
    '/track-request': {
      id: '/track-request'
      path: '/track-request'
      fullPath: '/track-request'
      preLoaderRoute: typeof TrackRequestImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/new-request': typeof NewRequestRoute
  '/track-request': typeof TrackRequestRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/new-request': typeof NewRequestRoute
  '/track-request': typeof TrackRequestRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/new-request': typeof NewRequestRoute
  '/track-request': typeof TrackRequestRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/chat' | '/new-request' | '/track-request'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/chat' | '/new-request' | '/track-request'
  id: '__root__' | '/' | '/chat' | '/new-request' | '/track-request'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRoute
  NewRequestRoute: typeof NewRequestRoute
  TrackRequestRoute: typeof TrackRequestRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRoute,
  NewRequestRoute: NewRequestRoute,
  TrackRequestRoute: TrackRequestRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/chat",
        "/new-request",
        "/track-request"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/chat": {
      "filePath": "chat.tsx"
    },
    "/new-request": {
      "filePath": "new-request.tsx"
    },
    "/track-request": {
      "filePath": "track-request.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
